name: Rust

permissions:
  contents: read

on:
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  RUSTFLAGS: -D warnings

jobs:
  check-and-test:
    strategy:
      matrix:
        features: ["", "derive", "derive,alloc", "derive,std", "digest", "digest,std"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 #v2
      with:
        cache-on-failure: "true"
    - name: Check
      run: cargo check -p udigest --no-default-features --features "${{ matrix.features }}"
    - name: Run tests
      run: cargo test -p udigest --lib --tests --no-default-features --features "${{ matrix.features }}"
  test-all-features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 #v2
      with:
        cache-on-failure: "true"
    - name: Check
      run: cargo check -p udigest --all-features
    - name: Run tests
      run: cargo test -p udigest --all-features
  run-examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 #v2
      with:
        cache-on-failure: "true"
    - name: Run example
      run: cargo run --example derivation --features derive,std
  check-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - name: Check formatting
      run: cargo fmt --all -- --check
  check-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 #v2
      with:
        cache-on-failure: "true"
    - name: Check docs
      run: RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 #v2
      with:
        cache-on-failure: "true"
    - name: Run clippy
      run: cargo clippy --all-features -- -D clippy::all
  clippy-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 #v2
      with:
        cache-on-failure: "true"
    - name: Run clippy
      run: cargo clippy --all-features --tests -- -D clippy::all
  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 #v2
      with:
        cache-on-failure: "true"
    - name: Install Miri
      run: |
        rustup toolchain install nightly --component miri
        rustup override set nightly
        cargo miri setup
    - name: Run Miri
      run: cargo miri test --all-features --lib -p udigest
  check-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 #v6.0.3
    - name: Check changelogs
      run: ./.github/changelog.sh
